# Generated by Django 2.2.10 on 2020-06-14 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20200613_0718'),
        ('profiles', '0002_delete_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritesProducts',
            new_name='FavoriteProducts',
        ),
        migrations.AlterModelOptions(
            name='favoriteproducts',
            options={'verbose_name_plural': 'Favorite Products'},
        ),
    ]
