# Generated by Django 2.2.10 on 2020-06-14 08:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20200613_0718'),
        ('profiles', '0003_auto_20200614_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteProducts',
            new_name='FavoritesProducts',
        ),
        migrations.AlterModelOptions(
            name='favoritesproducts',
            options={'verbose_name_plural': 'Favorites Products'},
        ),
    ]
