# Generated by Django 2.2.10 on 2020-06-16 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200614_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesproducts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
