# Generated by Django 2.2.10 on 2020-06-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
