# Generated by Django 2.2.10 on 2020-06-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Postpaid', 'Postpaid'), ('Prepaid', 'Prepaid'), ('Pay-as-you-go', 'Pay-as-you-go')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contract',
            field=models.CharField(choices=[('6 Months', '6 Months'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('More than 2 Years', 'More than 2 Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='telco',
            field=models.CharField(choices=[('Singtel', 'Singtel'), ('Starhub', 'Starhub'), ('M1', 'M1')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
