# Generated by Django 2.2.10 on 2020-06-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200611_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='contract_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='contract',
        ),
        migrations.AddField(
            model_name='product',
            name='monthly_bill',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='monthly_data',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sms',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='telco',
            field=models.CharField(choices=[('Singtel', 'Singtel'), ('Starhub', 'Starhub'), ('M1', 'M1'), ('Circles.Life', 'Circles.Life'), ('CMLink', 'CMLink'), ('MyRepublic', 'MyRepublic'), ('giga!', 'giga!'), ('redONE', 'redONE'), ('GOMO', 'GOMO'), ('Zero1', 'Zero1'), ('VIVIFI', 'VIVIFI'), ('TPG Mobile', 'TPG Mobile'), ('Grid Mobile', 'GridMobile')], max_length=200, null=True),
        ),
    ]
