# Generated by Django 2.2.10 on 2020-06-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200613_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='monthly_data',
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='contract_length',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
