# Generated by Django 2.2.10 on 2020-06-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200613_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='call_time',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='contract_length',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='sms',
            field=models.CharField(max_length=120),
        ),
    ]
