# Generated by Django 2.2.13 on 2020-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200629_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contract_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.IntegerField(),
        ),
    ]
